name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: Run linter
      run: flake8 app.py

  build-and-push:
    # Эта джоба запустится ТОЛЬКО если джоба test завершилась успешно!
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v4
      
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        # Здесь мы формируем имя образа: твой_логин/имя_репозитория:тег
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/my-first-app:latest
